name: send_to_join
description: Flutter project.
publish_to: 'none'

version: 2.2.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider:
  provider:
  shared_preferences:
  url_launcher:
  http:
  fluttertoast:
  easy_dynamic_theme:
  sqflite:
  jiffy:
  linkwell:
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.6.9
  share_plus: ^8.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true